### ISSUE TITLE
How to store DB as a file instead of IndexedDB

### ISSUE THREAD

**Issue by bestHandsome** [rodrigoelicer/electron-testing-app-2#2]
i want to read local .db file  
![image](https://user-images.githubusercontent.com/19648679/35322576-c591fffc-0125-11e8-82bc-951e1f7abb1e.png)  
![image](https://user-images.githubusercontent.com/19648679/35322596-d3c45c82-0125-11e8-973b-56a0f2fd0c3f.png)  but this can't satisfy with me, the file path will save in IndexDb, , can you tell me the way to fit it?
![image](https://user-images.githubusercontent.com/19648679/35322726-3b648c22-0126-11e8-9a28-722a8379dcfc.png)  the result is not i want to get.  

i see your issues in this herf (https://github.com/louischatriot/nedb/issues/482)  but in my respository, i'm not use webpack , i use angular-cli

**Comment by rodrigoelicer** [comment]
Hi xjj8567320,

So it's been a while that I struggled with that issue, which was indeed a pain in the ass. Could you explain it a bit more so I can understand it better?

Right now are you saving everything on IndexedDB? What's that user.db file you show on the images? I see you have values in there, so you're already saving things on persistent file, or am I wrong?

Just to clarify, angular-cli do uses webpack, so maybe you can find something by looking at [this](https://stackoverflow.com/questions/39187556/angular-cli-where-is-webpack-config-js-file-new-2017-feb-ng-eject). Also did you tried what Yvanovitch suggested on the issue you just quoted? Try with `window.require('fs')` somewhere in your code.

I'd like to help more, really, but right now I'm not aware of all this because it's 1 year since I don't touch it. However I think it'd helpful if you upload your repository somewhere so I can look at it.

**Comment by bestHandsome** [comment]
as you know, the user.db file is what i want to  use in my repository,  but it does't work. you can try my reposity to  resolve my problem https://github.com/xjj8567320/nedb-test, i don't know how to How to store the user.db as a file in reposity instead of  in browser's IndexedDB

**Comment by rodrigoelicer** [comment]
Sorry for the delay, but unfortunately I really don't remember a lot of this angular-webpack thingy and also don't have the time to check it right now. I really hope you can fix it asap though!
